apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ssm
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: pawankct91/dev-ssm
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: ssm-service
  namespace: ssm
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
---
