apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ssm-dep
  namespace: ssm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ssm-dep
    spec:
      containers:
      - name: ssm-dep
        image: pawankct91/dev-fedora:${BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ssm-service
  namespace: ssm
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
   type: NodePort
  selector:
    app: ssm-dep
---
