apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ssm
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pawankct91/dev-ssm
        ports:
        - containerPort: 8053
---
kind: Service
apiVersion: v1
metadata:
  name: ssm-service
  namespace: ssm
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8053
      nodePort: 30001
  type: NodePort
---
