apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ssm-dep
  namespace: ssm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ssm-dep
    spec:
      containers:
      - name: ssm-dep
        image: reg-dhc.app.corpintra.net/example/busybox:1.26
        imagePullPolicy: Always
        securityContext:
           runAsUser: 1000
           runAsNonRoot: true
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ssm-service
  namespace: ssm
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ssm-dep
---
