apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ssm
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pawankct91/pawankct91/dev-fedora:${BUILD_NUMBER}"
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: ssm-service
  namespace: ssm
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort
---
